ShoeStore_Nhom2_Web2/Controllers/CRUDController.cs
using Microsoft.AspNetCore.Mvc;
using ShoeStore_Nhom2_Web2.Models;
using ShoeStore_Nhom2_Web2.Repositories;
#nullable disable
namespace ShoeStore_Nhom2_Web2.Controllers
{
	public class CRUDController : Controller
	{
		private readonly IAdminShoeRepository _adminShoeRepository;
		private readonly IHttpContextAccessor _contextAccessor;

		public CRUDController(IAdminShoeRepository adminShoeRepository, IHttpContextAccessor contextAccessor)
		{
			_adminShoeRepository = adminShoeRepository;
			_contextAccessor = contextAccessor;
		}

		// GET: CRUDController
		public async Task<IActionResult> Index()
		{
			var Role = _contextAccessor.HttpContext.Session.GetString("Role");

			if (string.IsNullOrEmpty(Role))
			{
				return StatusCode(StatusCodes.Status401Unauthorized, $"Bạn không có quyền truy cập vào tài nguyên này, vui lòng đăng nhập bằng Admin Account và thử lại.");
			}

			if (Role.Contains("Read") && !Role.Contains("Write"))
			{
				return StatusCode(StatusCodes.Status401Unauthorized, "Hệ thống phát hiện bạn không phải Admin, Bạn không có quyền truy cập vào tài nguyên này, vui lòng thử lại.");
			}

			var response = await _adminShoeRepository.GetAllShoesAsync();
			if (response.IsSuccessStatusCode)
			{
				var shoes = await response.Content.ReadFromJsonAsync<List<Shoe_Model>>();
				return View(shoes);
			}
			else
			{
				return StatusCode((int)response.StatusCode);
			}
		}

		// GET: CRUDController/Details/5
		public async Task<IActionResult> Detail(int id)
		{
			var response = await _adminShoeRepository.GetShoeByIdAsync(id);
			if (response.IsSuccessStatusCode)
			{
				var shoe = await response.Content.ReadFromJsonAsync<Shoe_Model>();
				return View(shoe);
			}
			else
			{
				return StatusCode((int)response.StatusCode);
			}
		}

		// GET: CRUDController/Create
		public IActionResult Create()
		{
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create(ShoeCreateDto shoeCreateDto)
		{
			var response = await _adminShoeRepository.CreateShoeAsync(shoeCreateDto);
			if (response.IsSuccessStatusCode)
			{
				return RedirectToAction(nameof(Index));
			}
			else
			{
				return StatusCode((int)response.StatusCode);
			}
		}

		// GET: CRUDController/Edit/5
		public async Task<IActionResult> Edit(int id)
		{
			var response = await _adminShoeRepository.GetShoeByIdAsync(id);
			if (response.IsSuccessStatusCode)
			{
				var shoe = await response.Content.ReadFromJsonAsync<Shoe_Model>();
				return View(shoe);
			}
			else
			{
				return StatusCode((int)response.StatusCode);
			}
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, Shoe_Model shoeModel)
		{
			var response = await _adminShoeRepository.UpdateShoeAsync(id, shoeModel);
			if (response.IsSuccessStatusCode)
			{
				return RedirectToAction(nameof(Index));
			}
			else
			{
				return StatusCode((int)response.StatusCode);
			}
		}

		// GET: CRUDController/Delete/5
		public async Task<IActionResult> Delete(int id)
		{
			var response = await _adminShoeRepository.GetShoeByIdAsync(id);
			if (response.IsSuccessStatusCode)
			{
				var shoe = await response.Content.ReadFromJsonAsync<Shoe_Model>();
				return View(shoe);
			}
			else
			{
				return StatusCode((int)response.StatusCode);
			}
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			var response = await _adminShoeRepository.DeleteShoeAsync(id);
			if (response.IsSuccessStatusCode)
			{
				return RedirectToAction(nameof(Index));
			}
			else
			{
				return StatusCode((int)response.StatusCode);
			}
		}
	}
}

ShoeStore_Nhom2_Web2/Controllers/ShopController.cs
using Microsoft.AspNetCore.Mvc;
using ShoeStore_Nhom2_Web2.Models;
using Newtonsoft.Json;
using ShoeStore_Nhom2_Web2.Repositories;
#nullable disable
namespace ShoeStore_Nhom2_Web2.Controllers
{
	public class ShopController : Controller
	{
		private readonly IShopRepository _shopRepository;
		private readonly IHttpContextAccessor _contextAccessor;

		public ShopController(IShopRepository shopRepository, IHttpContextAccessor httpContextAccessor)
		{
			_shopRepository = shopRepository;
			_contextAccessor = httpContextAccessor;
		}

		public IActionResult Register()
		{
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> RegisterP(RegisterRequestDTO requestDTO)
		{
			var response = await _shopRepository.RegisterUserAsync(requestDTO);
			if (response.IsSuccessStatusCode)
			{
				ViewBag.Ok = "Thông báo: Đăng ký thành công, đăng nhập ngay!";
				return View("Register");
			}
			else
			{
				ViewBag.Fail = "Lỗi: Xác nhận mật khẩu không chính xác, vui lòng thử lại";
				return View("Register");
			}
		}

		public IActionResult Login()
		{
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> Loginp(LoginViewModel loginModel)
		{
			var CheckLoginn = loginModel.Username;
			var response = await _shopRepository.LoginUserAsync(loginModel);
			if (response.IsSuccessStatusCode)
			{
				_contextAccessor.HttpContext.Session.SetString("CheckLoginn", CheckLoginn); // Session

				var token = await response.Content.ReadFromJsonAsync<LoginResponseDTO>();
				var tokenn = token.JwtToken;
				var Roles = token.Roles.ToList();
				_contextAccessor.HttpContext.Session.SetString("JWTToken", tokenn); // Session
				var RoleJson = JsonConvert.SerializeObject(Roles);
				HttpContext.Session.SetString("Role", RoleJson); // Session
				ViewData["Token"] = tokenn;

				if (Roles.Contains("Write"))
				{
					var CheckLogin = "Vien";
					_contextAccessor.HttpContext.Session.SetString("CheckLogin", CheckLogin); // Session
					return RedirectToAction("Index", "Home");
				}
				else if (Roles.Contains("Read"))
				{
					return RedirectToAction("Index", "Home");
				}
				else if (!string.IsNullOrEmpty(tokenn))
				{
					return RedirectToAction("Index", "Home");
				}
			}
			else
			{
				ViewBag.InvalidCredentials = "Invalid username or password.";
				return View("Login");
			}

			return BadRequest();
		}

		public IActionResult Logout()
		{
			_contextAccessor.HttpContext.Session.Remove("JWTToken");
			_contextAccessor.HttpContext.Session.Remove("Role");
			_contextAccessor.HttpContext.Session.Remove("CheckLogin");
			_contextAccessor.HttpContext.Session.Remove("CheckLoginn");

			return RedirectToAction("Login");
		}

		public async Task<IActionResult> Category(string brand = null, string color = null)
		{
			var response = await _shopRepository.GetFilteredShoesAsync(brand, color);
			if (response.IsSuccessStatusCode)
			{
				var shoes = await response.Content.ReadFromJsonAsync<List<Shoe_Model>>();
				return View(shoes);
			}
			else
			{
				return StatusCode((int)response.StatusCode);
			}
		}

		public async Task<IActionResult> CategoryP(int page = 1, int pageSize = 10)
		{
			ViewData["page"] = page;
			ViewData["size"] = pageSize;
			if (page <= 0 || pageSize <= 0) return BadRequest("Số trang và kích thước trang phải từ 1 trở lên");

			var response = await _shopRepository.GetShoesByPageAsync(page, pageSize);
			if (response.IsSuccessStatusCode)
			{
				var shoes = await response.Content.ReadFromJsonAsync<List<Shoe_Model>>();
				return View("Category", shoes);
			}
			else
			{
				return StatusCode((int)response.StatusCode);
			}
		}

		public async Task<IActionResult> Detail(int id)
		{
			var response = await _shopRepository.GetShoeDetailAsync(id);
			if (response.IsSuccessStatusCode)
			{
				var shoe = await response.Content.ReadFromJsonAsync<Shoe_Model>();
				return View(shoe);
			}
			else
			{
				return StatusCode((int)response.StatusCode);
			}
		}

		public IActionResult Cart()
		{
			var Role = _contextAccessor.HttpContext.Session.GetString("Role");

			if (string.IsNullOrEmpty(Role))
			{
				return StatusCode(StatusCodes.Status401Unauthorized, "Bạn phải đăng nhập để dùng chức năng này. ");
			}
			if (Role.Contains("Read"))
			{
				return View();
			}
			return BadRequest();
		}

		public IActionResult Checkout()
		{
			return View();
		}

		public IActionResult Confirm()
		{
			return View();
		}

		public IActionResult Contact()
		{
			return View();
		}
	}
}

ShoeStore_Nhom2_Web2/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject IHttpContextAccessor HttpContext
@{
    var CheckLogin = HttpContext.HttpContext?.Session.GetString("CheckLogin");
    var CheckLoginn = HttpContext.HttpContext?.Session.GetString("CheckLoginn");
}
<!DOCTYPE html>
<html lang="zxx" class="no-js">

<head>
    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon-->
    <link rel="shortcut icon" href="img/fav.png">
    <!-- Author Meta -->
    <meta name="author" content="CodePixar">
    <!-- Meta Description -->
    <meta name="description" content="">
    <!-- Meta Keyword -->
    <meta name="keywords" content="">
    <!-- meta character set -->
    <meta charset="UTF-8">
    <!-- Site Title -->
    <title>Shoe Store G2</title>
    <!--
        CSS
        ============================================= -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="stylesheet" href="~/css/linearicons.css">
    <link rel="stylesheet" href="~/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/themify-icons.css">
    <link rel="stylesheet" href="~/css/bootstrap.css">
    <link rel="stylesheet" href="~/css/owl.carousel.css">
    <link rel="stylesheet" href="~/css/nice-select.css">
    <link rel="stylesheet" href="~/css/nouislider.min.css">
    <link rel="stylesheet" href="~/css/ion.rangeSlider.css" />
    <link rel="stylesheet" href="~/css/ion.rangeSlider.skinFlat.css" />
    <link rel="stylesheet" href="~/css/magnific-popup.css">
    <link rel="stylesheet" href="~/css/main.css">
</head>

<body>

    <!-- Start Header Area -->
    <header class="header_area sticky-header">
        <div class="main_menu">
            <nav class="navbar navbar-expand-lg navbar-light main_box">
                <div class="container">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <a class="navbar-brand logo_h" asp-controller="Home" asp-action="Index"><img src="~/img/logo (2).jpg" alt="" width="50" height="50"> Store - G2</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
                        <ul class="nav navbar-nav menu_nav ml-auto">
                            <li class="nav-item active"><a class="nav-link" asp-controller="Home" asp-action="Index">Trang chủ</a></li>
                            <li class="nav-item submenu dropdown">
                                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                                   aria-expanded="false">SHOP</a>
                                <ul class="dropdown-menu">
                                    <li class="nav-item"><a class="nav-link" asp-controller="Shop" asp-action="Category">Danh mục sản phẩm</a></li>
                                    <li class="nav-item"><a class="nav-link" asp-controller="Shop" asp-action="Cart">Giỏ hàng</a></li>
                                </ul>
                            </li>
                            <li class="nav-item"><a class="nav-link" asp-controller="Shop" asp-action="ConTact">Contact</a></li>
                            @if (!string.IsNullOrEmpty(CheckLogin))
                            {
                                <li class="nav-item"><a class="nav-link" asp-controller="CRUD" asp-action="Index">CRUD</a></li>

                            }
                            @if (!string.IsNullOrEmpty(CheckLoginn))
                            {
                                <li class="nav-item"><a class="nav-link" asp-controller="Shop" asp-action="Login"><p>Chào mừng @CheckLoginn</p></a></li>
                                <li class="nav-item"><a class="nav-link" asp-controller="Shop" asp-action="Logout">Logout</a></li>

                            }
   
                            else
                            {
                                <li class="nav-item"><a class="nav-link" asp-controller="Shop" asp-action="Login">Login/Register</a></li>


                            }
 
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
        <div class="search_input" id="search_input_box">
            <div class="container">
                <form class="d-flex justify-content-between">
                    <input type="text" class="form-control" id="search_input" placeholder="Tìm kiếm ở dây">
                    <button type="submit" class="btn"></button>
                    <span class="lnr lnr-cross" id="close_search" title="Close Search"></span>
                </form>
            </div>
        </div>
    </header>
    <div class="container">

        @RenderBody()
    </div>
    <!-- start footer Area -->
    <footer class="footer-area section_gap">
        <div class="container">
            <div class="row">
                <div class="col-lg-3  col-md-6 col-sm-6">
                    <div class="single-footer-widget">
                        <h6>Về chúng tôi</h6>
                        <p>
                            Nhóm sinh viên thực hiện dự án học phần Web Programing 2
                        </p>
                    </div>
                </div>
                <div class="col-lg-4  col-md=6 col-sm-6">
                    <div class="single-footer-widget">
                        <h6>Tin mới</h6>
                        <p>Luôn hiển thị thông tin mới nhất của chúng tôi</p>
                        <div class="" id="mc_embed_signup">

                            <form target="_blank" novalidate="true" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
                                  method="get" class="form-inline">

                                <div class="d-flex flex-row">

                                    <input class="form-control" name="EMAIL" placeholder="Nhập email của bạn" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Email '"
                                           required="" type="email">


                                    <button class="click-btn btn btn-default"><i class="fa fa-long-arrow-right" aria-hidden="true"></i></button>
                                    <div style="position: absolute; left: -5000px;">
                                        <input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value="" type="text">
                                    </div>

                                    <!-- <div class="col-lg-4 col-md-4">
                                                <button class="bb-btn btn"><span class="lnr lnr-arrow-right"></span></button>
                                            </div>  -->
                                </div>
                                <div class="info"></div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3  col-md-6 col-sm-6">
                    <div class="single-footer-widget mail-chimp">
                        <h6 class="mb-20">Instragram Feed</h6>
                        <ul class="instafeed d-flex flex-wrap">
                            <li><img src="~/img/i1.jpg" alt=""></li>
                            <li><img src="~/img/i2.jpg" alt=""></li>
                            <li><img src="~/img/i3.jpg" alt=""></li>
                            <li><img src="~/img/i4.jpg" alt=""></li>
                            <li><img src="~/img/i5.jpg" alt=""></li>
                            <li><img src="~/img/i6.jpg" alt=""></li>
                            <li><img src="~/img/i7.jpg" alt=""></li>
                            <li><img src="~/img/i8.jpg" alt=""></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-2 col-md-6 col-sm-6">
                    <div class="single-footer-widget">
                        <h6>Follow chúng tôi</h6>
                        <p>Để chúng tôi hòa nhập với bạn</p>
                        <div class="footer-social d-flex align-items-center">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="footer-bottom d-flex justify-content-center align-items-center flex-wrap">
                <p class="footer-text m-0">
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
                <p>
                    Mẫu này được tham khảo và phát triển bởi nhóm 2 | Nguyễn Thanh Viễn - Nguyễn Quốc Việt - Chương Minh Tuấn
                </p>
            </div>
        </div>
    </footer>
    <!-- End footer Area -->

    <script src="~/js/vendor/jquery-2.2.4.min.js"></script>
    <script src="~/js/vendor/bootstrap.min.js"></script>
    <script src="~/js/jquery.ajaxchimp.min.js"></script>
    <script src="~/js/jquery.nice-select.min.js"></script>
    <script src="~/js/jquery.sticky.js"></script>
    <script src="~/js/nouislider.min.js"></script>
    <script src="~/js/countdown.js"></script>
    <script src="~/js/jquery.magnific-popup.min.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/gmaps.min.js"></script>
    <script src="~/js/main.js"></script>
    @RenderSection("Scripts", required: false)

</body>

</html>